# The Docker image that will be used to build your app
image: node:lts

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp web.html .public/index.html
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - main